"""
Certificate PDF Generator

Generates an AVFA certificate PDF and embeds a QR code
that points to the certificate verification endpoint.

The certificate number is supplied by the certificate
issuance system.

QR generation is handled by the QR module.
SHA-256 hashing, digital signatures, and database storage
are handled by separate modules.
"""

from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Optional
from uuid import UUID

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)

from QR.qr_generator import generate_qr_code


@dataclass
class Certificate:
    """Represents the AVFA certificate database schema."""

    id: UUID
    certificate_number: str

    institution_id: UUID
    issuer_id: UUID

    student_name: str
    student_roll_no: str
    course_name: str
    issue_date: date

    marks: Optional[str] = None
    cgpa: Optional[str] = None

    sha256_hash: str = ""
    digital_signature: str = ""

    batch_id: Optional[UUID] = None

    qr_code_url: Optional[str] = None
    pdf_url: Optional[str] = None

    status: str = "ISSUED"

    revocation_reason: Optional[str] = None
    revoked_at: Optional[datetime] = None
    created_at: Optional[datetime] = None


def generate_certificate_pdf(
    certificate: Certificate,
    certificate_number: str,
    output_path: str,
    institution_name: str,
    verification_base_url: str,
) -> str:
    """
    Generate an AVFA certificate PDF with an embedded QR code.

    The certificate number is supplied by the certificate
    issuance system.

    Parameters
    ----------
    certificate:
        Certificate data.

    certificate_number:
        Certificate number generated by the issuance system.

    output_path:
        Path where the PDF will be saved.

    institution_name:
        Institution name displayed on the certificate.

    verification_base_url:
        Base URL of the certificate verification endpoint.

        Example:
        http://localhost:8000/verify

    Returns
    -------
    str
        Path of the generated PDF.
    """

    # ---------------------------------------------------------
    # VALIDATION
    # ---------------------------------------------------------

    if certificate.status != "ISSUED":
        raise ValueError(
            f"Cannot generate PDF for certificate with status "
            f"'{certificate.status}'."
        )

    if not certificate_number:
        raise ValueError(
            "Certificate number cannot be empty."
        )

    if not institution_name:
        raise ValueError(
            "Institution name cannot be empty."
        )

    if not verification_base_url:
        raise ValueError(
            "Verification base URL cannot be empty."
        )

    # ---------------------------------------------------------
    # OUTPUT PATH
    # ---------------------------------------------------------

    output_file = Path(output_path)

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ---------------------------------------------------------
    # GENERATE QR CODE
    # ---------------------------------------------------------

    qr_output_path = (
        output_file.parent
        / f"{certificate_number}_qr.png"
    )

    qr_path = generate_qr_code(
        certificate_number=certificate_number,
        verification_base_url=verification_base_url,
        output_path=str(qr_output_path),
    )

    # ---------------------------------------------------------
    # PDF DOCUMENT
    # ---------------------------------------------------------

    document = SimpleDocTemplate(
        str(output_file),
        pagesize=A4,
        rightMargin=25 * mm,
        leftMargin=25 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()

    # ---------------------------------------------------------
    # STYLES
    # ---------------------------------------------------------

    institution_style = ParagraphStyle(
        "Institution",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        fontSize=20,
        leading=24,
        spaceAfter=15,
    )

    title_style = ParagraphStyle(
        "CertificateTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=24,
        leading=30,
        spaceAfter=15,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=13,
        leading=18,
        spaceAfter=12,
    )

    student_style = ParagraphStyle(
        "StudentName",
        parent=styles["Heading2"],
        alignment=TA_CENTER,
        fontSize=22,
        leading=28,
        spaceBefore=8,
        spaceAfter=8,
    )

    normal_center = ParagraphStyle(
        "NormalCenter",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=12,
        leading=18,
    )

    course_style = ParagraphStyle(
        "Course",
        parent=normal_center,
        fontSize=16,
        leading=20,
        spaceBefore=8,
        spaceAfter=15,
    )

    label_style = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
    )

    footer_style = ParagraphStyle(
        "Footer",
        parent=normal_center,
        fontSize=8,
        leading=11,
    )

    # ---------------------------------------------------------
    # CERTIFICATE CONTENT
    # ---------------------------------------------------------

    story = []

    story.append(
        Paragraph(
            institution_name.upper(),
            institution_style,
        )
    )

    story.append(
        Paragraph(
            "CERTIFICATE OF ACHIEVEMENT",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "This is to certify that",
            subtitle_style,
        )
    )

    story.append(
        Paragraph(
            certificate.student_name.upper(),
            student_style,
        )
    )

    story.append(
        Paragraph(
            f"Roll Number: "
            f"<b>{certificate.student_roll_no}</b>",
            normal_center,
        )
    )

    story.append(
        Spacer(1, 10 * mm)
    )

    story.append(
        Paragraph(
            "has successfully completed the course",
            normal_center,
        )
    )

    story.append(
        Paragraph(
            f"<b>{certificate.course_name}</b>",
            course_style,
        )
    )

    # ---------------------------------------------------------
    # CERTIFICATE DETAILS
    # ---------------------------------------------------------

    details = [
        [
            Paragraph(
                "<b>Certificate Number</b>",
                label_style,
            ),
            certificate_number,
        ],
        [
            Paragraph(
                "<b>Issue Date</b>",
                label_style,
            ),
            certificate.issue_date.strftime("%d-%m-%Y"),
        ],
    ]

    if certificate.marks is not None:
        details.append(
            [
                Paragraph(
                    "<b>Marks</b>",
                    label_style,
                ),
                str(certificate.marks),
            ]
        )

    if certificate.cgpa is not None:
        details.append(
            [
                Paragraph(
                    "<b>CGPA</b>",
                    label_style,
                ),
                str(certificate.cgpa),
            ]
        )

    details_table = Table(
        details,
        colWidths=[
            60 * mm,
            80 * mm,
        ],
        hAlign="CENTER",
    )

    details_table.setStyle(
        TableStyle(
            [
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.7,
                    colors.black,
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
            ]
        )
    )

    story.append(details_table)

    story.append(
        Spacer(1, 12 * mm)
    )

    # ---------------------------------------------------------
    # QR CODE
    # ---------------------------------------------------------

    qr_image = Image(
        qr_path,
        width=35 * mm,
        height=35 * mm,
    )

    qr_table = Table(
        [
            [qr_image],
            [
                Paragraph(
                    "Scan to verify certificate",
                    footer_style,
                )
            ],
        ],
        colWidths=[
            50 * mm,
        ],
        hAlign="CENTER",
    )

    qr_table.setStyle(
        TableStyle(
            [
                (
                    "ALIGN",
                    (0, 0),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    3,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    3,
                ),
            ]
        )
    )

    story.append(qr_table)

    story.append(
        Spacer(1, 12 * mm)
    )

    # ---------------------------------------------------------
    # SIGNATURE AREA
    # ---------------------------------------------------------

    signature_table = Table(
        [
            [
                "________________________",
                "________________________",
            ],
            [
                "Authorized Signatory",
                "Institution Authority",
            ],
        ],
        colWidths=[
            70 * mm,
            70 * mm,
        ],
        hAlign="CENTER",
    )

    signature_table.setStyle(
        TableStyle(
            [
                (
                    "ALIGN",
                    (0, 0),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "FONTNAME",
                    (0, 1),
                    (-1, 1),
                    "Helvetica-Bold",
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    4,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    4,
                ),
            ]
        )
    )

    story.append(signature_table)

    story.append(
        Spacer(1, 10 * mm)
    )

    # ---------------------------------------------------------
    # CERTIFICATE ID
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            f"Certificate ID: "
            f"<b>{certificate_number}</b>",
            normal_center,
        )
    )

    story.append(
        Spacer(1, 6 * mm)
    )

    # ---------------------------------------------------------
    # FOOTER
    # ---------------------------------------------------------

    story.append(
        Paragraph(
            "This certificate is digitally verifiable through "
            "the Authenticity Validator for Academia (AVFA).",
            footer_style,
        )
    )

    # ---------------------------------------------------------
    # BUILD PDF
    # ---------------------------------------------------------

    document.build(story)

    return str(output_file)