"""
Certificate PDF Generator

Generates an AVFA certificate PDF and embeds a QR code
that points to the certificate verification endpoint.

The certificate number is supplied by the certificate
issuance system.

QR generation is handled by the QR module.
SHA-256 hashing, digital signatures, and database storage
are handled by separate modules.
"""

import re
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Optional
from uuid import UUID
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from qr.qr_generator import generate_qr_code


@dataclass
class Certificate:
    """Represents the AVFA certificate database schema."""

    id: UUID
    certificate_number: str

    institution_id: UUID
    issuer_id: UUID

    student_name: str
    student_roll_no: str
    course_name: str
    issue_date: date

    marks: Optional[str] = None
    total_marks: Optional[str] = None
    result_status: Optional[str] = None
    cgpa: Optional[str] = None

    sha256_hash: str = ""
    digital_signature: str = ""

    batch_id: Optional[UUID] = None

    qr_code_url: Optional[str] = None
    pdf_url: Optional[str] = None

    status: str = "ISSUED"

    revocation_reason: Optional[str] = None
    revoked_at: Optional[datetime] = None
    created_at: Optional[datetime] = None


def generate_certificate_pdf(
    certificate: Certificate,
    certificate_number: str,
    output_path: str,
    institution_name: str,
    verification_base_url: str,
) -> str:
    """
    Generate an AVFA certificate PDF with an embedded QR code.

    Parameters
    ----------
    certificate:
        Certificate data.

    certificate_number:
        Certificate number generated by the issuance system.

    output_path:
        Path where the PDF will be saved.

    institution_name:
        Institution name displayed on the certificate.

    verification_base_url:
        Base URL of the certificate verification endpoint.

        Example:
        http://localhost:8000/verify

    Returns
    -------
    str
        Path of the generated PDF.
    """

    # ---------------------------------------------------------
    # VALIDATION
    # ---------------------------------------------------------

    if certificate.status != "ISSUED":
        raise ValueError(
            f"Cannot generate PDF for certificate with status "
            f"'{certificate.status}'."
        )

    if not certificate_number:
        raise ValueError(
            "Certificate number cannot be empty."
        )

    if certificate.certificate_number != certificate_number:
        raise ValueError(
            "Certificate number mismatch between certificate "
            "data and certificate_number argument."
        )

    if not institution_name:
        raise ValueError(
            "Institution name cannot be empty."
        )

    if not verification_base_url:
        raise ValueError(
            "Verification base URL cannot be empty."
        )

    if not certificate.student_name:
        raise ValueError(
            "Student name cannot be empty."
        )

    if not certificate.student_roll_no:
        raise ValueError(
            "Student roll number cannot be empty."
        )

    if not certificate.course_name:
        raise ValueError(
            "Course name cannot be empty."
        )

    # Prevent unsafe certificate numbers from being used
    # as filenames.
    if not re.fullmatch(
        r"(CERT-\d{4}-[A-Za-z0-9_-]+|AVFA-[A-Za-z0-9_-]+|[A-Za-z0-9_-]+)",
        certificate_number,
    ):
        raise ValueError(
            "Invalid certificate number format."
        )

    # ---------------------------------------------------------
    # OUTPUT PATH
    # ---------------------------------------------------------

    output_file = Path(output_path)

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ---------------------------------------------------------
    # PDF DOCUMENT
    # ---------------------------------------------------------

    document = SimpleDocTemplate(
        str(output_file),
        pagesize=A4,
        rightMargin=25 * mm,
        leftMargin=25 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
    )

    styles = getSampleStyleSheet()

    # ---------------------------------------------------------
    # STYLES
    # ---------------------------------------------------------

    institution_style = ParagraphStyle(
        "Institution",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        fontSize=20,
        leading=24,
        spaceAfter=4,
    )

    title_style = ParagraphStyle(
        "CertificateTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=24,
        leading=30,
        spaceAfter=4,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=13,
        leading=18,
        spaceAfter=6,
    )

    student_style = ParagraphStyle(
        "StudentName",
        parent=styles["Heading2"],
        alignment=TA_CENTER,
        fontSize=22,
        leading=28,
        spaceBefore=4,
        spaceAfter=4,
    )

    normal_center = ParagraphStyle(
        "NormalCenter",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=12,
        leading=18,
    )

    course_style = ParagraphStyle(
        "Course",
        parent=normal_center,
        fontSize=16,
        leading=20,
        spaceBefore=4,
        spaceAfter=4,
    )

    label_style = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
    )

    footer_style = ParagraphStyle(
        "Footer",
        parent=normal_center,
        fontSize=8,
        leading=11,
    )

    # ---------------------------------------------------------
    # TEMPORARY QR DIRECTORY
    # ---------------------------------------------------------

    with TemporaryDirectory() as temp_dir:

        qr_output_path = (
            Path(temp_dir)
            / f"{certificate_number}_qr.png"
        )

        qr_path = generate_qr_code(
            certificate_number=certificate_number,
            verification_base_url=verification_base_url,
            output_path=str(qr_output_path),
        )

        # -----------------------------------------------------
        # CERTIFICATE CONTENT
        # -----------------------------------------------------

        story = []

        # Institution name
        story.append(
            Paragraph(
                escape(institution_name.upper()),
                institution_style,
            )
        )

        # Certificate title
        story.append(
            Paragraph(
                "CERTIFICATE OF ACHIEVEMENT",
                title_style,
            )
        )

        # Subtitle
        story.append(
            Paragraph(
                "This is to certify that",
                subtitle_style,
            )
        )

        # Student name
        story.append(
            Paragraph(
                escape(certificate.student_name.upper()),
                student_style,
            )
        )

        # Roll number
        story.append(
            Paragraph(
                f"Roll Number: "
                f"<b>{escape(certificate.student_roll_no)}</b>",
                normal_center,
            )
        )

        story.append(
            Spacer(1, 4 * mm)
        )

        # Course description
        story.append(
            Paragraph(
                "has successfully completed the course",
                normal_center,
            )
        )

        # Course name
        story.append(
            Paragraph(
                f"<b>{escape(certificate.course_name)}</b>",
                course_style,
            )
        )

        # -----------------------------------------------------
        # CERTIFICATE DETAILS
        # -----------------------------------------------------

        if isinstance(certificate.issue_date, (datetime, date)):
            formatted_date = certificate.issue_date.strftime(
                "%d-%m-%Y"
            )
        else:
            formatted_date = str(certificate.issue_date)

        details = [
            [
                Paragraph(
                    "<b>Certificate Number</b>",
                    label_style,
                ),
                escape(certificate_number),
            ],
            [
                Paragraph(
                    "<b>Issue Date</b>",
                    label_style,
                ),
                escape(formatted_date),
            ],
        ]

        # Parse marks and total marks for presentation
        marks_obtained_str = str(certificate.marks) if certificate.marks is not None else None
        total_marks_str = str(certificate.total_marks) if certificate.total_marks is not None else None

        if marks_obtained_str:
            # Check if composite "450 / 500"
            if "/" in marks_obtained_str and not total_marks_str:
                display_marks = marks_obtained_str
            elif total_marks_str:
                try:
                    m_val = float(re.search(r"(\d+(?:\.\d+)?)", marks_obtained_str).group(1))
                    t_val = float(re.search(r"(\d+(?:\.\d+)?)", total_marks_str).group(1))
                    pct = (m_val / t_val) * 100.0 if t_val > 0 else 0.0
                    display_marks = f"{m_val:.2f} / {t_val:.2f} ({pct:.1f}%)"
                except Exception:
                    display_marks = f"{marks_obtained_str} / {total_marks_str}"
            else:
                display_marks = marks_obtained_str

            details.append(
                [
                    Paragraph(
                        "<b>Marks (Obtained / Total)</b>",
                        label_style,
                    ),
                    escape(display_marks),
                ]
            )

        # Evaluation / Result Status (PASSED / FAILED)
        eval_status = str(certificate.result_status or "PASSED").strip().upper()
        if "PASS" in eval_status:
            eval_html = f"<font color='#00875A'><b>{escape(eval_status)}</b></font>"
        else:
            eval_html = f"<font color='#DE350B'><b>{escape(eval_status)}</b></font>"

        details.append(
            [
                Paragraph(
                    "<b>Evaluation / Result</b>",
                    label_style,
                ),
                Paragraph(
                    eval_html,
                    label_style,
                ),
            ]
        )

        if certificate.cgpa is not None:
            details.append(
                [
                    Paragraph(
                        "<b>CGPA</b>",
                        label_style,
                    ),
                    escape(str(certificate.cgpa)),
                ]
            )

        details_table = Table(
            details,
            colWidths=[
                60 * mm,
                80 * mm,
            ],
            hAlign="CENTER",
        )

        details_table.setStyle(
            TableStyle(
                [
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.7,
                        colors.black,
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "LEFTPADDING",
                        (0, 0),
                        (-1, -1),
                        8,
                    ),
                    (
                        "RIGHTPADDING",
                        (0, 0),
                        (-1, -1),
                        8,
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                ]
            )
        )

        story.append(details_table)

        story.append(
            Spacer(1, 12 * mm)
        )

        # -----------------------------------------------------
        # QR CODE
        # -----------------------------------------------------

        qr_image = Image(
            qr_path,
            width=35 * mm,
            height=35 * mm,
        )

        qr_table = Table(
            [
                [qr_image],
                [
                    Paragraph(
                        "Scan to verify certificate",
                        footer_style,
                    )
                ],
            ],
            colWidths=[
                50 * mm,
            ],
            hAlign="CENTER",
        )

        qr_table.setStyle(
            TableStyle(
                [
                    (
                        "ALIGN",
                        (0, 0),
                        (-1, -1),
                        "CENTER",
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        3,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        3,
                    ),
                ]
            )
        )

        story.append(qr_table)

        story.append(
            Spacer(1, 12 * mm)
        )

        # -----------------------------------------------------
        # SIGNATURE AREA
        # -----------------------------------------------------

        signature_table = Table(
            [
                [
                    "________",
                    "________",
                ],
                [
                    "Authorized Signatory",
                    "Institution Authority",
                ],
            ],
            colWidths=[
                70 * mm,
                70 * mm,
            ],
            hAlign="CENTER",
        )

        signature_table.setStyle(
            TableStyle(
                [
                    (
                        "ALIGN",
                        (0, 0),
                        (-1, -1),
                        "CENTER",
                    ),
                    (
                        "FONTNAME",
                        (0, 1),
                        (-1, 1),
                        "Helvetica-Bold",
                    ),
                    (
                        "FONTSIZE",
                        (0, 0),
                        (-1, -1),
                        10,
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        4,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        4,
                    ),
                ]
            )
        )

        story.append(signature_table)

        story.append(
            Spacer(1, 4 * mm)
        )

        # -----------------------------------------------------
        # CERTIFICATE ID
        # -----------------------------------------------------

        story.append(
            Paragraph(
                f"Certificate ID: "
                f"<b>{escape(certificate_number)}</b>",
                normal_center,
            )
        )

        story.append(
            Spacer(1, 6 * mm)
        )

        # -----------------------------------------------------
        # FOOTER
        # -----------------------------------------------------

        story.append(
            Paragraph(
                "This certificate is digitally verifiable through "
                "the Authenticity Validator for Academia (AVFA).",
                footer_style,
            )
        )

        # -----------------------------------------------------
        # BUILD PDF
        # -----------------------------------------------------

        try:
            document.build(story)

        except Exception:
            # Remove partially generated PDF if ReportLab
            # fails during document generation.
            if output_file.exists():
                output_file.unlink()

            raise

    return str(output_file)