"""
QR Code Generator

Generates a QR code for an AVFA certificate.

The certificate number is supplied by the certificate issuance
system. The QR contains the certificate verification URL.
"""

from pathlib import Path

import qrcode


def generate_qr_code(
    certificate_number: str,
    verification_base_url: str,
    output_path: str,
) -> str:
    """
    Generate a QR code for a certificate.

    Parameters
    ----------
    certificate_number:
        Certificate number generated by the issuance system.

        Example:
        CERT-2026-F7BCAB87

    verification_base_url:
        Base URL of the verification endpoint.

        Example:
        http://localhost:8000/verify

    output_path:
        Path where the QR image will be saved.

    Returns
    -------
    str
        Path of the generated QR image.
    """

    if not certificate_number:
        raise ValueError(
            "Certificate number cannot be empty."
        )

    if not verification_base_url:
        raise ValueError(
            "Verification base URL cannot be empty."
        )

    verification_base_url = verification_base_url.rstrip("/")

    verification_url = (
        f"{verification_base_url}/{certificate_number}"
    )

    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=10,
        border=4,
    )

    qr.add_data(verification_url)
    qr.make(fit=True)

    qr_image = qr.make_image(
        fill_color="black",
        back_color="white",
    )

    output_file = Path(output_path)

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    qr_image.save(output_file)

    return str(output_file)